version: "3.8"

services:
  bot:
    build: .
    container_name: telegram_bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .:/app
    command: ["python", "src/bot.py"]
